added common vlcrc commands for conveniance

diff --git a/bin/music b/bin/music
--- a/bin/music
+++ b/bin/music
@@ -2,7 +2,6 @@
 #
 # set volume and play vlc playlists
 # 
-## TODO merge with vlcrc, e.g., music next, music stop, music pause, music play, music vol 45
 #
 export DISPLAY=":0"
 export PATH=$PATH:~/bin
@@ -10,13 +9,13 @@ export PATH=$PATH:~/bin
 playlist_dir=/home/twarnock/Music/0_playlist
 playlist_file=Classical.xspf
 volume=45
-Z_OPT=""
+Z_OPT=" -Z "
 
 
 ##
 ## gather variables from getopts
 ##
-usage() { echo "Usage: [options] [playlist-file]" && grep " .)\ #" $0; }
+usage() { echo "Usage: [options] [playlist-file|command]" && grep " .)\ #" $0; }
 while getopts ":d:v:zlh" arg; do
   case $arg in
     d) # Specify playlist directory
@@ -25,8 +24,8 @@ while getopts ":d:v:zlh" arg; do
     v) # Specify volume (default is 45)
       volume=${OPTARG}
       ;;
-    z) # randomize playlist
-      Z_OPT=" -Z "
+    z) # play in order, default is random order
+      Z_OPT=""
       ;;
     l) # list playlists
       ls -1 $playlist_dir
@@ -41,8 +40,8 @@ done
 shift $((OPTIND - 1))
 if [ $# -gt 0 ]; then
   playlist_file="$@"
-  ## append .xspf if no extension given
-  if [ "${playlist_file%.*}" == "$playlist_file" ]; then
+  ## append .xspf if no extension given, and the relavant file exists
+  if [ "${playlist_file%.*}" == "$playlist_file" -a -r "$playlist_dir/$playlist_file"".xspf" ]; then
     playlist_file=$playlist_file".xspf"
   fi
 fi
@@ -52,11 +51,29 @@ fi
 if [ -r "$playlist_dir/$playlist_file" ]; then
   pkill vlc
   volume.sh $volume 2>&1 >/dev/null
-  nohup vlc -Z "$playlist_dir/$playlist_file" >/dev/null 2>&1 &
+  nohup vlc $Z_OPT "$playlist_dir/$playlist_file" >/dev/null 2>&1 &
 else
-  (>&2 echo "could not read $playlist_file in $playlist_dir")
-  usage
-  exit 1
+  ## no playlist, check if this is a vlcrc command
+  case $playlist_file in
+   -|0|+)
+     echo "Got it!" ;;
+   p|play|pause)
+     vlcrc pause ;;
+   k|kill|s|stop|end|term|terminate)
+     pkill vlc ;;
+   n|next) 
+     vlcrc next ;;
+   prev)
+     vlcrc prev ;;
+   z|rand|random)
+     vlcrc random ;;
+   *)
+    (>&2 echo "could not read $playlist_file in $playlist_dir")
+    usage
+    exit 1
+  esac
+
+
 fi
 
 
